/**
 * !!! Skeleton code generated by SAP BusinessOne WebClient UI API VS Code Extension. Do not modify it. !!!
 * This script is to start the development server. It will serve the webapp folder and src folder of the modules.
 * By default, the development server will be started at http://localhost:8081.
 */

const express = require('express')
const fs = require('fs');
const cors = require('cors');
const path = require('path');
const morgan = require('morgan');
require("colors");

const settingsFilePath = path.join(__dirname, '.vscode', 'settings.json');
const getWorkspacePort = () => {
  const settingsFileContent = fs.readFileSync(settingsFilePath, 'utf-8');
  const settings = JSON.parse(settingsFileContent);
  return settings["WebClient.debugServer.port"];
}

let app = express();
app.use(cors({ origin: '*' }));
app.use(morgan('tiny'));

const appsContent = JSON.parse(fs.readFileSync(__dirname + "/app.json", 'utf-8'));
console.log("SAP Business One Web Client Extensions".bold);
console.log("Start serving....".green);
appsContent.applications.forEach(function (obj) {
  let module = obj.path.split("/");
  module = obj.path.replace(module[0] + "/", "")
  app.use(`/${obj.path}`, (req, res, next) => {
    req.accepts('application/json');
    var result = req.url.match(/\/gulpfile.js$/)
    if (result) {
      return res.status(404).end('Cannot GET ' + req.url)
    }
    return next();
  })

  app.use(`/${obj.path}`, express.static(`${module}`));    //serve webapp folder
  obj.path = obj.path.replace("/webapp", "/src");
  module = module.replace("/webapp", "/src")

  app.use(`/${obj.path}`, express.static(`${module}`));    //serve src folder
  console.log(`Module source file path : ${module}`);
});
app.use('/app.json', express.static('app.json'));

const port = fs.existsSync(settingsFilePath) ? getWorkspacePort() : 8081;
app.listen(port, 'localhost');
console.log("Serving modules on port: ".green + `${port}`.yellow);
console.log(`Dev server is working at: http://localhost:${port}\n`);